### ISSUE TITLE
Astro 4 is not compatible

### ISSUE THREAD

**Issue by dallyh** [e3stpavel/astro-nanointl#9]
### Astro version

4.5.8

### What's wrong?

Hello, I wanted to give this integration a try, but the current dependency for Astro is set to 3.0.0. Are there any plans currently to update the dependency?

### What did you expect?

Successfull install.

### What are you using?

hybrid

### Adapter

None

**Comment by e3stpavel** [comment]
Hey! Thank you for adding this issue.

Tbh, I think about changing the API a bit to fit the new [built-in Astro i18n API](https://docs.astro.build/en/guides/internationalization/). I wanted to remove some overhead and utilize [Content Collections API](https://docs.astro.build/en/guides/content-collections/) for declaring the translations as well. However, if you want to use it asap let me know and I will apply quick patch to make it work with Astro `^4.0.0 `.

**Comment by dallyh** [comment]
I haven't had a chance to try this integration, however from the docs I could see the potential of fitting the integration to use the built-in i18n like having it read the locale config from it, maybe also auto detect the current locale in pages (like Paraglide.js integration does) and such. Using content collections for translations could be great too, but I can't judge because I'm really used to having my translations in JSON or YAML files and then using some sort of a VSCode extension to manage them (like i18n-ally).
